[package]
name = "git-ticket-summary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.14"
regex = "1.6.0"
structopt = "0.3.26"
