#!/bin/sh

VERSION="0.1.1"

TICKET_ID=$1
REF=$2

if [ -z $TICKET_ID ]; then
	echo "Error: missing <ticket-id> argument"
	echo "Usage: git-ticket-summary <ticket-id> <branch>"
	exit 1
fi

if [ -z $REF ]; then
	echo "Error: missing <branch> argument"
	echo "Usage: git-ticket-summary <ticket-id> <branch>"
	exit 2
fi

# LOCAL_BRANCH=`git name-rev --name-only HEAD`
LOCAL_BRANCH=$REF
TRACKING_BRANCH=`git config branch.$LOCAL_BRANCH.merge`
TRACKING_REMOTE=`git config branch.$LOCAL_BRANCH.remote`
TRACKING_REMOTE_URL=`git config remote.$TRACKING_REMOTE.url`

# replace refs/heads/ with empty string
SHORT_TRACKING_BRANCH=${TRACKING_BRANCH/refs\/heads\//}

FIXED_REMOTE_URL=${TRACKING_REMOTE_URL/git@github.com:/"https://github.com/"}
BASE_URL=${FIXED_REMOTE_URL%????}

COMMIT_BASE_URL="${BASE_URL}/commit/"

echo "\nTicket Summary - v${VERSION}\n"

echo "ticket: ${TICKET_ID}"
echo "repository: ${TRACKING_REMOTE_URL}"

echo "\n## Commits\n"
git log ${REF} --pretty=format:"%C(yellow)%h%Creset - %G? -%C(red)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset $COMMIT_BASE_URL%H" --grep=$TICKET_ID

echo "\n## Files created / deleted / modified\n"

INVOLVED_FILES=`git log ${REF} --pretty=format:"%H" --grep=$TICKET_ID | xargs -n 1 git diff-tree --no-commit-id --name-only -r `

echo "$INVOLVED_FILES" | sort | uniq | xargs -n 1 -I % echo ${BASE_URL}/blob/${SHORT_TRACKING_BRANCH}/%
